version: "3.9"

x-server-tune: &server-tune
  restart: unless-stopped
  sysctls:
    - net.core.somaxconn=65535
  ulimits:
    nproc: 65535
    nofile: 500000

services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - ACME_AGREE=true
    env_file:
      - .env
    depends_on:
      - kuma
      - ntfy
    <<: *server-tune

  kuma:
    container_name: kuma
    image: louislam/uptime-kuma
    volumes:
      - "./data/uptime-kuma:/app/data"
    expose:
      - "3001"
    <<: *server-tune

  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy
    volumes:
      - ./data/ntfy:/var/lib/ntfy
    command:
      - serve
    environment:
      - NTFY_LISTEN_HTTP=:8000
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh
    env_file:
      - .env
    expose:
      - "8000"
    <<: *server-tune

  smtp:
    container_name: smtp
    image: bytemark/smtp
    expose:
      - 25
    env_file:
      - .env
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
